name: easy_in_app_review_flutter_example
description: "Example app demonstrating easy_in_app_review_flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  easy_in_app_review_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
